# Generated by Django 5.2.8 on 2025-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='Україна', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_freelance',
            field=models.BooleanField(default=True, verbose_name='Фріланс-проєкти'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Постійна віддалена робота'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
