# Generated by Django 5.2.8 on 2025-11-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Веб-розробка'), ('backend', 'Backend (Python, PHP, Node.js)'), ('frontend', 'Frontend (HTML, CSS, JS, React)'), ('mobile', 'Мобільна розробка (Android, iOS)'), ('gamedev', 'Розробка ігор (Unity, Unreal)'), ('design', 'Дизайн (UI/UX, Логотипи, Арт)'), ('qa', 'Тестування (QA Manual/Auto)'), ('devops', 'DevOps та Системне адміністрування'), ('datascience', 'Data Science, AI та Боти'), ('marketing', 'Маркетинг, SEO та SMM'), ('copywriting', 'Копірайтинг та Переклади'), ('video', 'Аудіо та Відеомонтаж'), ('other', 'Інше')], default='other', max_length=50),
        ),
    ]
