# Generated by Django 5.2.8 on 2025-11-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Знання мов'),
        ),
    ]
