# Generated by Django 5.2.8 on 2025-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_order_executor_order_status_alter_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_freelance',
            field=models.BooleanField(default=False, verbose_name='Шукаю проєкти'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Тільки віддалено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='client', max_length=20),
        ),
    ]
